# Generated by Django 4.0.4 on 2022-06-19 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_imagen_producto', models.CharField(default='default_value', max_length=50)),
                ('nombre_producto', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='Armando casas', max_length=30)),
                ('password', models.CharField(default='●●●●●●●', max_length=15)),
                ('dir_entrega', models.CharField(blank=True, default='av. falsa 123', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_pedido', models.DateField()),
                ('total', models.IntegerField()),
                ('estado', models.CharField(max_length=15)),
                ('id_productos', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='back.producto')),
            ],
        ),
    ]
